import { test } from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { cli, listWith, makeWorld } from './helpers.ts'

test('exit codes: 0 done, 1 refused, 2 could not be asked; usage', () => {
  const w = makeWorld()
  assert.equal(cli(w).code, 2, 'no command')
  assert.equal(cli(w, '--help').code, 0)
  assert.match(cli(w, '--help').stdout, /pod up/)
  assert.equal(cli(w, 'nope').code, 2)
  assert.equal(cli(w, 'up').code, 2, 'up needs --image')
  assert.equal(cli(w, 'submit').code, 2, 'submit needs a directory')
  assert.equal(cli(w, 'show').code, 2)
  assert.equal(cli(w, 'wait').code, 2)
  assert.equal(cli(w, 'cancel').code, 2)
  assert.equal(cli(w, 'show', 'nowhere').code, 2, 'a job that does not exist')
  assert.equal(cli(w, 'wait', 'nowhere').code, 2)
  assert.equal(cli(w, 'cancel', 'nowhere').code, 2)
  assert.equal(cli(w, 'status', '--runtime', 'lxc').code, 2)
  assert.ok(existsSync(join(w.state, '.gitignore')), 'the state directory is made on any command')
  assert.ok(existsSync(join(w.state, 'work_queue', '.running')) && existsSync(join(w.state, 'work_queue', '.done')))
  assert.equal(cli(w, 'list').code, 0, 'the queue commands need no runtime')
  assert.ok(!w.calls().length, 'and ask it nothing')
})

test('up: created from the image with the queue mounted and the worker settings in its environment; started when stopped; left alone when running', () => {
  const w = makeWorld()
  writeFileSync(join(w.dir, 'pod.yaml'), `mounts: ['${join(w.dir, 'extra')}:/heai/extra']\nresources: { cpus: 4, memory: 8G }\nworkers: 2\ntimeout: 30m\n`)
  const envFile = join(w.dir, 'creds.env')
  writeFileSync(envFile, 'X=1\n')
  const created = cli(w, 'up', '--image', 'aw3/workshop', '--env-from', envFile, '--mount', '/x:/y', '--poll', '5s', '--timeout', '2h')
  assert.equal(created.code, 0, created.stderr)
  assert.match(created.stdout, /Created and started heai-workshop from aw3\/workshop/)
  const run = w.calls().find((c) => c.argv[0] === 'run')!
  assert.deepEqual(run.argv, [
    'run', '-d', '--name', 'heai-workshop', '-l', 'heai.tool=pod',
    '-v', `${join(w.state, 'work_queue')}:/work_queue`, '-v', `${join(w.dir, 'extra')}:/heai/extra`, '-v', '/x:/y',
    '-e', 'WORKERS=2', '-e', 'TIMEOUT=2h', '-e', 'POLL=5s',
    '--env-file', envFile, '-c', '4', '-m', '8G', 'aw3/workshop'
  ])
  assert.equal(cli(w, 'up', '--image', 'aw3/workshop', '--env-from', '/nope.env').code, 2, 'a missing env file is refused before the runtime is asked')
  assert.equal(cli(w, 'up', '--image', 'x', '--workers', 'two').code, 2)
  assert.equal(cli(w, 'up', '--image', 'x', '--timeout', '90').code, 2, 'the worker wants a unit')
  assert.equal(cli(w, 'up', '--image', 'x', '--timeout', '0').code, 0, '0 is no limit')
  assert.ok(w.calls().at(-1)!.argv.includes('TIMEOUT=0'))

  w.replies([{ when: ['list', '--all'], stdout: listWith('heai-workshop', 'stopped') }])
  assert.match(cli(w, 'up', '--image', 'aw3/workshop').stdout, /Started heai-workshop/)
  assert.ok(w.calls().some((c) => c.argv[0] === 'start' && c.argv[1] === 'heai-workshop'))

  w.replies([{ when: ['list', '--all'], stdout: listWith('heai-workshop', 'running') }])
  assert.match(cli(w, 'up', '--image', 'aw3/workshop').stdout, /already running/)
  assert.match(cli(w, 'up', '--container', 'other', '--image', 'aw3/workshop').stdout, /Created and started other/, '--container picks the container')
  const other = w.calls().at(-1)!.argv
  assert.ok(other.includes('WORKERS=2') && other.includes('TIMEOUT=30m') && !other.some((a) => a.startsWith('POLL=')), 'the configuration\'s settings, and only what was set')
})

test('down: refused while a job runs, forced past it, and a no-op when stopped or absent', () => {
  const w = makeWorld()
  assert.match(cli(w, 'down').stdout, /does not exist/)
  w.replies([{ when: ['list', '--all'], stdout: listWith('heai-workshop', 'stopped') }])
  assert.match(cli(w, 'down').stdout, /already stopped/)
  w.replies([{ when: ['list', '--all'], stdout: listWith('heai-workshop', 'running') }])
  cli(w, 'submit', w.jobDir('t1'))
  w.claim('t1')
  const refused = cli(w, 'down')
  assert.equal(refused.code, 1)
  assert.match(refused.stderr, /1 job is still running/)
  assert.ok(!w.calls().some((c) => c.argv[0] === 'stop'))
  assert.equal(cli(w, 'down', '--force').code, 0)
  assert.ok(w.calls().some((c) => c.argv[0] === 'stop' && c.argv[1] === 'heai-workshop'))
  w.finish('t1', {})
  assert.match(cli(w, 'down').stdout, /Stopped heai-workshop/)
})

test('status: the runtime\'s word and the queue\'s counts, as text and JSON; 1 when the container is down', () => {
  const w = makeWorld()
  const absent = cli(w, 'status')
  assert.equal(absent.code, 1)
  assert.match(absent.stdout, /does not exist/)
  cli(w, 'submit', w.jobDir('a'))
  cli(w, 'submit', w.jobDir('b'))
  cli(w, 'submit', w.jobDir('c'))
  cli(w, 'submit', w.jobDir('d'))
  w.claim('b')
  w.claim('c')
  w.finish('c', { status: 'failed', exit: 3 })
  w.claim('d')
  w.finish('d', {})
  w.replies([{ when: ['list', '--all'], stdout: listWith('heai-workshop', 'running') }])
  const s = cli(w, 'status')
  assert.equal(s.code, 0, s.stderr)
  assert.match(s.stdout, /container {2}heai-workshop {2}running/)
  assert.match(s.stdout, /queue {6}1 queued, 1 running, 2 done \(1 failed, 1 ok\)/)
  const j = JSON.parse(cli(w, 'status', '--json').stdout)
  assert.deepEqual(j, { container: { name: 'heai-workshop', state: 'running', running: true, image: 'docker.io/library/alpine:latest' }, queue: { queued: 1, running: 1, done: 2, byStatus: { failed: 1, ok: 1 } } })
})

test('build: the base from the tool\'s image directory; extended images FROM the base; all of them at once', () => {
  const w = makeWorld()
  const imageDir = join(import.meta.dirname, '..', 'image')
  const r = cli(w, 'build', 'base', '--tag', 'aw3/base')
  assert.equal(r.code, 0, r.stderr)
  assert.deepEqual(w.calls().find((c) => c.argv[0] === 'build')!.argv, ['build', '-t', 'aw3/base', '-f', join(imageDir, 'Containerfile'), imageDir])
  assert.equal(cli(w, 'build', 'base', '--image-dir', w.dir).code, 2, 'no Containerfile there')
  assert.ok(existsSync(join(imageDir, 'worker', 'main.go')), 'the worker\'s source ships beside the Containerfile that compiles it')
  assert.ok(existsSync(join(imageDir, 'example', 'Containerfile')), 'an extended image to copy ships too')

  mkdirSync(join(w.dir, 'images', 'workshop'), { recursive: true })
  writeFileSync(join(w.dir, 'images', 'workshop', 'Containerfile'), 'ARG BASE\nFROM ${BASE}\n')
  mkdirSync(join(w.dir, 'images', 'ops'), { recursive: true })
  writeFileSync(join(w.dir, 'images', 'ops', 'Containerfile'), 'ARG BASE\nFROM ${BASE}\n')
  writeFileSync(join(w.dir, 'pod.yaml'), 'base: aw3/base\nimages:\n  aw3/workshop: images/workshop\n  aw3/ops: ./images/ops\n')

  const one = cli(w, 'build', 'aw3/workshop')
  assert.equal(one.code, 0, one.stderr)
  assert.match(one.stdout, /Built aw3\/workshop from .* on aw3\/base/)
  assert.deepEqual(w.calls().at(-1)!.argv, ['build', '-t', 'aw3/workshop', '-f', join(w.dir, 'images/workshop/Containerfile'), '--build-arg', 'BASE=aw3/base', join(w.dir, 'images/workshop')])
  assert.equal(cli(w, 'build', 'aw3/unknown').code, 2, 'an image the configuration does not name needs --image-dir')
  assert.equal(cli(w, 'build', 'aw3/unknown', '--image-dir', join(w.dir, 'images/ops')).code, 0)

  const all = cli(w, 'build')
  assert.equal(all.code, 0, all.stderr)
  const builds = w.calls().filter((c) => c.argv[0] === 'build').slice(-3)
  assert.deepEqual(builds.map((b) => b.argv[2]), ['aw3/base', 'aw3/workshop', 'aw3/ops'], 'the base first, then every image in order')
  assert.equal(builds[0]!.argv[3], '-f')
  assert.equal(builds[0]!.argv[4], join(imageDir, 'Containerfile'), 'the base from the tool\'s own image/ when baseDir: is unset')
})

test('shell: an interactive bash in the container', () => {
  const w = makeWorld()
  assert.equal(cli(w, 'shell').code, 0)
  assert.deepEqual(w.calls().at(-1)!.argv, ['exec', '-it', 'heai-workshop', 'bash', '-l'])
  cli(w, 'shell', '--container', 'ops')
  assert.equal(w.calls().at(-1)!.argv[2], 'ops')
})

test('submit, list, show, wait, cancel: the protocol from the host, with the worker played by hand', async () => {
  const w = makeWorld()
  const src = w.jobDir('t1-cache', { 'prompt.md': 'cache it\n', 'repos/app/README.md': 'hi\n' })
  const s = cli(w, 'submit', src)
  assert.equal(s.code, 0, s.stderr)
  assert.equal(s.stdout, 't1-cache\n')
  assert.ok(existsSync(join(src, 'prompt.md')), 'a copy; the source stays')
  assert.equal(readFileSync(join(w.dirs.queue, 't1-cache', 'repos', 'app', 'README.md'), 'utf8'), 'hi\n')
  assert.equal(cli(w, 'submit', src).code, 1, 'a name that exists is refused')
  assert.equal(cli(w, 'submit', src, '--name', '.hidden').code, 2, 'a dotted name would never be seen')
  assert.equal(cli(w, 'submit', src, '--name', 'a b').code, 2)
  assert.equal(cli(w, 'submit', join(w.dir, 'nowhere')).code, 2)

  const moved = w.jobDir('t2', { 'run.sh': 'echo hi\n' })
  assert.equal(cli(w, 'submit', moved, '--move', '--timeout', '45m').stdout, 't2\n')
  assert.ok(!existsSync(moved), '--move takes the directory')
  assert.deepEqual(JSON.parse(readFileSync(join(w.dirs.queue, 't2', 'job.json'), 'utf8')), { timeout: '45m' })
  assert.equal(cli(w, 'submit', w.jobDir('t3', { 'job.json': '{"agent":"claude"}\n' }), '--timeout', '1h').code, 0)
  assert.deepEqual(JSON.parse(readFileSync(join(w.dirs.queue, 't3', 'job.json'), 'utf8')), { agent: 'claude', timeout: '1h' }, 'the timeout joins what job.json already says')
  assert.equal(cli(w, 'submit', src, '--name', 't4', '--timeout', '90').code, 2, 'the worker wants a unit')
  assert.ok(!existsSync(join(w.dirs.queue, 't4')) && !existsSync(join(w.dirs.queue, '.tmp-t4')), 'nothing left behind when refused')

  let list = cli(w, 'list')
  assert.match(list.stdout, /^t1-cache {2}queued {4}queued/m)
  assert.match(list.stdout, /^t2 {8}queued {4}queued/m)
  assert.deepEqual(JSON.parse(cli(w, 'list', '--json').stdout).map((j: { name: string; place: string }) => [j.name, j.place]), [['t1-cache', 'queued'], ['t2', 'queued'], ['t3', 'queued']])

  const notDone = cli(w, 'wait', 't1-cache', '--timeout', '300')
  assert.equal(notDone.code, 2, 'wait\'s own timeout')
  assert.match(notDone.stderr, /not done after 300/)
  assert.equal(cli(w, 'wait', 't1-cache', '--timeout', 'soon').code, 2)

  w.claim('t1-cache')
  const running = cli(w, 'show', 't1-cache')
  assert.equal(running.code, 0, running.stderr)
  assert.match(running.stdout, /^place {5}running$/m)
  assert.match(running.stdout, /^worker {4}w1$/m)
  assert.match(cli(w, 'list').stdout, /^t1-cache {2}running {3}running +2026-09-25T10:00:00/m)

  assert.match(cli(w, 'cancel', 't1-cache').stdout, /Asked the worker to stop/)
  assert.ok(existsSync(join(w.dirs.running, 't1-cache', 'cancel')), 'a running job gets a cancel file')
  assert.match(cli(w, 'cancel', 't2').stdout, /Canceled t2; it never ran/)
  const t2 = JSON.parse(readFileSync(join(w.dirs.done, 't2', 'result.json'), 'utf8'))
  assert.equal(t2.status, 'canceled')
  assert.equal(t2.worker, 'heai-pod')
  assert.equal(cli(w, 'cancel', 't2').code, 1, 'already done')

  w.finish('t1-cache', { status: 'canceled', exit: -1, signal: 'TERMINATED' }, { stdout: 'line 1\nline 2\nline 3\n', stderr: 'oops\n' })
  const waited = cli(w, 'wait', 't1-cache')
  assert.equal(waited.code, 1, 'settled badly')
  assert.equal(waited.stdout, 'canceled\n')
  const shown = cli(w, 'show', 't1-cache', '--lines', '2')
  assert.match(shown.stdout, /^status {4}canceled$/m)
  assert.match(shown.stdout, /^signal {4}TERMINATED$/m)
  assert.match(shown.stdout, /^duration {2}1m31s$/m)
  assert.match(shown.stdout, /--- log\/stdout \(last 2 lines\)\nline 2\nline 3\n--- log\/stderr/)
  assert.ok(!/line 1/.test(shown.stdout))
  const shownJson = JSON.parse(cli(w, 'show', 't1-cache', '--json').stdout)
  assert.equal(shownJson.place, 'done')
  assert.equal(shownJson.result.status, 'canceled')
  assert.equal(shownJson.log.stderr, 'oops\n')

  w.claim('t3')
  w.finish('t3', {})
  const ok = cli(w, 'wait', 't3', '--json')
  assert.equal(ok.code, 0)
  assert.equal(JSON.parse(ok.stdout).result.status, 'ok')
  list = cli(w, 'list')
  assert.match(list.stdout, /^t1-cache {2}done {6}canceled {3}-1 {4}1m31s {5}2026-09-25T10:00:00\.000Z$/m)
  assert.match(list.stdout, /^t3 {8}done {6}ok {9}0 {5}1m31s/m)
})
