import { test } from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { defaultRuntime, ensureState, parseConfig, parseDuration, positiveInt, readConfig, resolvePaths, SCHEMA_PATH, schemaProblems, UsageError, workerDuration } from '../src/config.ts'
import { parseMount, workerEnv } from '../src/box.ts'
import { makeWorld } from './helpers.ts'

test('paths: --dir, then HEAI_DIR, then the cwd; the state and the configuration sit in it', () => {
  const w = makeWorld()
  const p = resolvePaths({}, { HEAI_DIR: w.dir }, '/elsewhere')
  assert.deepEqual(p, { dir: w.dir, state: join(w.dir, 'pod'), config: join(w.dir, 'pod.yaml') })
  assert.equal(resolvePaths({ dir: '/x' }, { HEAI_DIR: w.dir }, '/elsewhere').dir, '/x', '--dir beats HEAI_DIR')
  assert.equal(resolvePaths({}, {}, w.dir).dir, w.dir, 'else the cwd')
  assert.equal(resolvePaths({ state: 's' }, {}, w.dir).state, join(w.dir, 's'))
  assert.equal(resolvePaths({}, { HEAI_POD_STATE: '/st' }, w.dir).state, '/st')
  assert.equal(resolvePaths({ config: 'c.yaml' }, {}, w.dir).config, join(w.dir, 'c.yaml'))
})

test('configuration: checked against the schema, ~ expanded, absent file is {}', () => {
  const w = makeWorld()
  const path = join(w.dir, 'pod.yaml')
  assert.deepEqual(readConfig(path), {})
  writeFileSync(path, 'runtime: docker\nname: heai-aw3\nbase: aw3/base\nbaseDir: ~/aw3/base\nimages:\n  aw3/workshop: ~/aw3/images/workshop\n  aw3/ops: images/ops\nenvFile: ~/.heai/aw3.env\nmounts:\n  - ~/aw3/flow/flows:/heai/flow\nresources: { cpus: 6, memory: 12G }\nworkers: 3\ntimeout: 2h\npoll: 500ms\n')
  const c = readConfig(path)
  assert.equal(c.runtime, 'docker')
  assert.equal(c.name, 'heai-aw3')
  assert.equal(c.base, 'aw3/base')
  assert.ok(c.baseDir!.endsWith('/aw3/base') && !c.baseDir!.startsWith('~'))
  assert.ok(c.images!['aw3/workshop']!.endsWith('/aw3/images/workshop') && !c.images!['aw3/workshop']!.startsWith('~'))
  assert.equal(c.images!['aw3/ops'], 'images/ops')
  assert.ok(c.envFile!.endsWith('/.heai/aw3.env') && !c.envFile!.startsWith('~'))
  assert.ok(c.mounts![0]!.endsWith('/aw3/flow/flows:/heai/flow') && !c.mounts![0]!.startsWith('~'))
  assert.deepEqual(c.resources, { cpus: 6, memory: '12G' })
  assert.equal(c.workers, 3)
  assert.equal(c.timeout, '2h')
  assert.equal(c.poll, '500ms')
  assert.throws(() => parseConfig('mounts: nope\n'), /\/mounts: must be a list of host:container strings/)
  assert.throws(() => parseConfig('mounts: [nocolon]\n'), /\/mounts\/0: must be host:container/)
  assert.throws(() => parseConfig('images: [a, b]\n'), /\/images: must be a mapping of image tag to directory/)
  assert.throws(() => parseConfig('images: { x: 1 }\n'), /\/images\/x: must be a path/)
  assert.throws(() => parseConfig('resources: { cpus: six }\n'), /\/resources\/cpus: must be a number/)
  assert.throws(() => parseConfig('resources: { disk: 1 }\n'), /\/resources: unknown key "disk"; the keys are cpus, memory/)
  assert.throws(() => parseConfig('runtime: lxc\n'), /\/runtime: must be apple, docker or podman/)
  assert.throws(() => parseConfig('workers: 0\n'), /\/workers: must be a positive whole number/)
  assert.throws(() => parseConfig('workers: 1.5\n'), /\/workers: must be a positive whole number/)
  assert.throws(() => parseConfig('timeout: 90\n'), /\/timeout: must be a duration like 1h, or 0/)
  assert.throws(() => parseConfig('poll: 0\n'), /\/poll: must be a duration like 2s/)
  assert.throws(() => parseConfig('image: aw3/workshop\n'), /\/: unknown key "image"; the keys are runtime, name, base/)
  assert.throws(() => parseConfig('- a list\n'), /must be a mapping/)
  assert.throws(() => parseConfig('a: [\n'), /not valid YAML/)
  assert.equal(schemaProblems({ runtime: 1, name: '' }).length, 2, 'every problem at once')
  assert.deepEqual(schemaProblems({}), [])
  assert.deepEqual(parseConfig(''), {})
  assert.deepEqual(parseConfig('resources: { memory: 12 }\n'), { resources: { memory: '12' } })
  assert.deepEqual(parseConfig('timeout: "0"\n'), { timeout: '0' })
  assert.ok(existsSync(SCHEMA_PATH), 'the schema ships with the tool')
  writeFileSync(path, '')
  assert.deepEqual(readConfig(path), {})
})

test('the state directory: work_queue with .running and .done, and a .gitignore of *', () => {
  const w = makeWorld()
  const s = ensureState(w.state)
  assert.deepEqual(s, { root: w.state, queue: join(w.state, 'work_queue'), running: join(w.state, 'work_queue', '.running'), done: join(w.state, 'work_queue', '.done') })
  assert.ok(existsSync(s.running) && existsSync(s.done))
  assert.equal(readFileSync(join(w.state, '.gitignore'), 'utf8'), '*\n')
  writeFileSync(join(w.state, '.gitignore'), 'mine\n')
  ensureState(w.state)
  assert.equal(readFileSync(join(w.state, '.gitignore'), 'utf8'), 'mine\n', 'an existing .gitignore is left alone')
})

test('durations, counts, mounts, the worker\'s environment, the default runtime', () => {
  assert.equal(parseDuration('250'), 250)
  assert.equal(parseDuration('30s'), 30_000)
  assert.equal(parseDuration('5m'), 300_000)
  assert.equal(parseDuration('2h'), 7_200_000)
  assert.equal(parseDuration('soon'), null)
  assert.equal(workerDuration('30m', '--timeout'), '30m')
  assert.equal(workerDuration('0', '--timeout'), '0')
  assert.throws(() => workerDuration('90', '--timeout'), UsageError)
  assert.throws(() => workerDuration('1d', '--timeout'), UsageError)
  assert.equal(positiveInt('3', '--workers'), 3)
  assert.throws(() => positiveInt('0', '--workers'), UsageError)
  assert.throws(() => positiveInt('two', '--workers'), UsageError)
  assert.deepEqual(parseMount('/a:/b'), { host: '/a', container: '/b' })
  assert.deepEqual(parseMount('/a:/b:ro'), { host: '/a', container: '/b:ro' }, 'the first colon splits')
  assert.throws(() => parseMount('/a'), UsageError)
  assert.throws(() => parseMount(':/c'), UsageError)
  assert.deepEqual(workerEnv({}), {})
  assert.deepEqual(workerEnv({ workers: 2, timeout: '0', poll: '1s' }), { WORKERS: '2', TIMEOUT: '0', POLL: '1s' })
  assert.equal(defaultRuntime('darwin'), 'apple')
  assert.equal(defaultRuntime('linux'), 'docker')
})
